@API_HostAddress = http://localhost:5255
@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmNjYTdkMC03NDAyLTRhOTYtODgzZS1kNjIxYmM3NGI2ZjMiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJqdGkiOiI2MTNhYThmNy0yMDNjLTRkZDAtOTYzOS0wOTI0N2NkZWVhZWIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc2ODc1NDQxNiwiaXNzIjoiTGVhcm5pbmdQbGF0Zm9ybSIsImF1ZCI6IkxlYXJuaW5nUGxhdGZvcm1Vc2VycyJ9.HLJ869NirMIZrgcWAfl9TQK9QglPQ9-9R9xsTUfx-xo
@user_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NTk4NDU4My1hNDQzLTRhYTYtODZkMC0xZGJjZjBmNDA2N2EiLCJlbWFpbCI6InVzZXIzQGV4YW1wbGUuY29tIiwianRpIjoiNWM0NjRkNWUtZGEwZC00MDM3LWE4MzItMzZjOTFlOTFiZWVlIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiR3Vlc3QiLCJleHAiOjE3Njg3NDUwMDQsImlzcyI6IkxlYXJuaW5nUGxhdGZvcm0iLCJhdWQiOiJMZWFybmluZ1BsYXRmb3JtVXNlcnMifQ.eX6LRbY83_0p26CaxVoG3nNhfrg8nv5c2siATXu0xfA
@instructor_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NTk4NDU4My1hNDQzLTRhYTYtODZkMC0xZGJjZjBmNDA2N2EiLCJlbWFpbCI6InVzZXIzQGV4YW1wbGUuY29tIiwianRpIjoiZTViZGE1NzQtZjM1My00M2QxLTg3YzgtNGNiZWU4YTQxYmE2IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiSW5zdHJ1Y3RvciIsImV4cCI6MTc2ODc1NDQzNSwiaXNzIjoiTGVhcm5pbmdQbGF0Zm9ybSIsImF1ZCI6IkxlYXJuaW5nUGxhdGZvcm1Vc2VycyJ9.UW7Dn0soQ8IP3wE7XN4rx3Mx-xn2u-_YzGE1_ijDpcc

### Modules and Lessons
### =================================================
@courseId = 8dc446bf-cfa7-4569-be65-a4f82c7012ac
@instructorId = 95984583-a443-4aa6-86d0-1dbcf0f4067a
### Module - Get Modules by Course ID
GET {{API_HostAddress}}/courses/{{courseId}}/modules
Accept: application/json

### Module - Create New Module for Course
POST {{API_HostAddress}}/courses/{{courseId}}/modules
Authorization: Bearer {{instructor_token}}
Content-Type: application/json

{
    "title": "Module 2: Basics",
    "description": "Covers the basic concepts and fundamentals."
}

### Module - Update Module by ID
@moduleId = fb456a6b-606a-4a18-90dd-af5bf5e19776
PUT {{API_HostAddress}}/modules/{{moduleId}}
Authorization: Bearer {{instructor_token}}
Content-Type: application/json

{
    "title": "Module 2: Basics - Updated",
    "description": "Updated basic concepts and fundamentals."
}

### Module - Delete Module by ID
DELETE {{API_HostAddress}}/modules/{{moduleId}}
Authorization: Bearer {{instructor_token}}
Accept: application/json

### Lesson - Get Lessons by Module ID
GET {{API_HostAddress}}/modules/{{moduleId}}/lessons
Accept: application/json

### Lesson - Create New Lesson for Module
POST {{API_HostAddress}}/modules/{{moduleId}}/lessons
Authorization: Bearer {{instructor_token}}
Content-Type: application/json

{
    "title": "Lesson 4: Lets Get Started",
    "description": "Introduction to getting started with the module.",
    "contentType": "video",
    "contentUrl": "https://example.com/lesson4-getting-started.mp4",
    "orderIndex": 4
}

### Lesson - Update Lesson by ID
@lessonId = 53c0d5ff-a93b-4355-94a6-fe2618d28172
PUT {{API_HostAddress}}/lessons/{{lessonId}}
Authorization: Bearer {{instructor_token}}
Content-Type: application/json

{
    "title": "Lesson 1: Course Introduction - Updated",
    "content": "Updated content for the course introduction lesson."
}

### Lesson - Delete Lesson by ID
DELETE {{API_HostAddress}}/lessons/{{lessonId}}
Authorization: Bearer {{instructor_token}}
Accept: application/json

### Lesson - Mark Lesson as Complete
POST {{API_HostAddress}}/lessons/{{lessonId}}/complete
Authorization: Bearer {{user_token}}
Accept: application/json
