@API_HostAddress = http://localhost:5255
@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmNjYTdkMC03NDAyLTRhOTYtODgzZS1kNjIxYmM3NGI2ZjMiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJqdGkiOiIwMGFhY2U3YS1mM2Y0LTQ0MDQtOWZhYS04MThmNGYyMWUzNzIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdGFmZiIsImV4cCI6MTc2ODU4NjQxOSwiaXNzIjoiTGVhcm5pbmdQbGF0Zm9ybSIsImF1ZCI6IkxlYXJuaW5nUGxhdGZvcm1Vc2VycyJ9.tWmEBN06sab5VnWwQC_MKjGTsSPte8bJ0y_VEUPmzhc
@user_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MjdkZTFmYy01ZDcwLTQzNDQtOGQ0NS0yNzFiMGM4YTAwMzQiLCJlbWFpbCI6InVzZXIyQGV4YW1wbGUuY29tIiwianRpIjoiNjM0OTViMmQtMGQyNy00ZmQ4LThmN2ItZDljYjliMjRhNzE3IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiR3Vlc3QiLCJleHAiOjE3Njg1ODYzOTksImlzcyI6IkxlYXJuaW5nUGxhdGZvcm0iLCJhdWQiOiJMZWFybmluZ1BsYXRmb3JtVXNlcnMifQ.rhHv1_exdR3x-2rw4SOFAJ27uj_mhjZx82BRKq6RN7c

GET {{API_HostAddress}}/health/
Accept: application/json

### Auth
### =================================================
### Auth - Register
POST {{API_HostAddress}}/auth/register
Content-Type: application/json

{
    "firstName": "John 6",
    "lastName": "Doe 6",
    "email": "user6@example.com",
    "password1": "Password123!",
    "password2": "Password123!"
}

### Auth - Login
POST {{API_HostAddress}}/auth/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "Password123!"
}

### Auth - Verify User
POST {{API_HostAddress}}/auth/verify
Authorization: Bearer {{user_token}}

### Auth - Forgot Password
POST {{API_HostAddress}}/auth/forgot-password
Content-Type: application/json

{
    "email": "user2@example.com"
}

### Auth - Reset Password
POST {{API_HostAddress}}/auth/reset-password
Content-Type: application/json

{
    "email": "user2@example.com",
    "token": "193167",
    "newPassword1": "NewPassword123!",
    "newPassword2": "NewPassword123!"
}

### User
### =================================================

# GET    /api/users/{id}
# GET    /api/users/{id}/public-profile

### User - Get Current User
GET {{API_HostAddress}}/users/me
Authorization: Bearer {{user_token}}
Accept: application/json

### User - Update Current User
PUT {{API_HostAddress}}/users/me
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "firstName": "John 2",
    "lastName": "Doe 2"
}

### User - Update Current User Password
PUT {{API_HostAddress}}/users/me/password
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "currentPassword": "AnotherPassword123!",
    "newPassword1": "AnotherPassword123!",
    "newPassword2": "AnotherPassword123!"
}

### User - Get User by ID
@userId = 927de1fc-5d70-4344-8d45-271b0c8a0034
GET {{API_HostAddress}}/users/{{userId}}
Authorization: Bearer {{admin_token}}
Accept: application/json

### User - Get User Public Profile by ID
GET {{API_HostAddress}}/users/{{userId}}/public-profile
Accept: application/json

### Course
### =================================================
# GET    /api/courses✅
# GET    /api/courses/{id}✅
# POST   /api/courses✅
# PUT    /api/courses/{id}✅
# DELETE /api/courses/{id}✅
# POST   /api/courses/{id}/publish
# POST   /api/courses/{id}/enroll
# DELETE /api/courses/{id}/unenroll
# GET    /api/courses/my-courses
# GET    /api/courses/my-enrollments
# GET    /api/courses/instructor-courses
# GET    /api/courses/{id}/students
# GET    /api/courses/recommended
# GET    /api/courses/trending
# POST   /api/courses/{id}/review

### Course - Get All Courses
GET {{API_HostAddress}}/courses
Accept: application/json

### Course - Get Course by ID
@courseId = 1
GET {{API_HostAddress}}/courses/{{courseId}}
Accept: application/json

### Course - Create New Course
POST {{API_HostAddress}}/courses    
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
    "title": "Introduction to Programming",
    "description": "Learn the basics of programming using Python.",
    "instructorId": "9bcca7d0-7402-4a96-883e-d621bc74b6f3",
    "category": "Programming",
    "price": 49.99
}

### Course - Update Course by ID
@courseId = 1
PUT {{API_HostAddress}}/courses/{{courseId}}
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
    "title": "Introduction to Programming - Updated",
    "description": "Learn the basics of programming using Python. Updated content included.",
    "instructorId": "9bcca7d0-7402-4a96-883e-d621bc74b6f3",
    "category": "Programming",
    "price": 59.99
}

### Course - Delete Course by ID
@courseId = 1
DELETE {{API_HostAddress}}/courses/{{courseId}}
Authorization: Bearer {{admin_token}}
Accept: application/json
